extends Node
class_name KeySpriteGlob

const w := 16

const coordswhite := {
	"(unset)": Rect2(5 * w, 6 * w, w, w),
	"a (physichal)": Rect2(5 * w, 6 * w, w, w),# TODO: ta bort kanske
	"left": Rect2(2 * w, 0 * w, w, w),
	"right": Rect2(3 * w, 0 * w, w, w),
	"up": Rect2(0 * w, 0 * w, w, w),
	"down": Rect2(1 * w, 0 * w, w, w),
	"a": Rect2(0 * w, 2 * w, w, w),
	"b": Rect2(1 * w, 2 * w, w, w),
	"c": Rect2(2 * w, 2 * w, w, w),
	"d": Rect2(3 * w, 2 * w, w, w),
	"e": Rect2(4 * w, 2 * w, w, w),
	"f": Rect2(5 * w, 2 * w, w, w),
	"g": Rect2(6 * w, 2 * w, w, w),
	"h": Rect2(7 * w, 3 * w, w, w),
	"i": Rect2(0 * w, 3 * w, w, w),
	"j": Rect2(1 * w, 3 * w, w, w),
	"k": Rect2(2 * w, 3 * w, w, w),
	"l": Rect2(3 * w, 3 * w, w, w),
	"m": Rect2(4 * w, 3 * w, w, w),
	"n": Rect2(5 * w, 3 * w, w, w),
	"o": Rect2(6 * w, 3 * w, w, w),
	"p": Rect2(7 * w, 3 * w, w, w),
	"q": Rect2(0 * w, 4 * w, w, w),
	"r": Rect2(1 * w, 4 * w, w, w),
	"s": Rect2(2 * w, 4 * w, w, w),
	"t": Rect2(3 * w, 4 * w, w, w),
	"u": Rect2(4 * w, 4 * w, w, w),
	"v": Rect2(5 * w, 4 * w, w, w),
	"w": Rect2(6 * w, 4 * w, w, w),
	"x": Rect2(7 * w, 4 * w, w, w),
	"y": Rect2(0 * w, 5 * w, w, w),
	"z": Rect2(1 * w, 5 * w, w, w),
}

const coordsblue := {
	"(unset)": Rect2(5 * w, 13 * w, w, w),
	"left": Rect2(2 * w, 7 * w, w, w),
	"right": Rect2(3 * w, 7 * w, w, w),
	"up": Rect2(0 * w, 7 * w, w, w),
	"down": Rect2(1 * w, 7 * w, w, w),
	"a": Rect2(0 * w, 9 * w, w, w),
	"b": Rect2(1 * w, 9 * w, w, w),
	"c": Rect2(2 * w, 9 * w, w, w),
	"d": Rect2(3 * w, 9 * w, w, w),
	"e": Rect2(4 * w, 9 * w, w, w),
	"f": Rect2(5 * w, 9 * w, w, w),
	"g": Rect2(6 * w, 9 * w, w, w),
	"h": Rect2(7 * w, 10 * w, w, w),
	"i": Rect2(0 * w, 10 * w, w, w),
	"j": Rect2(1 * w, 10 * w, w, w),
	"k": Rect2(2 * w, 10 * w, w, w),
	"l": Rect2(3 * w, 10 * w, w, w),
	"m": Rect2(4 * w, 10 * w, w, w),
	"n": Rect2(5 * w, 10 * w, w, w),
	"o": Rect2(6 * w, 10 * w, w, w),
	"p": Rect2(7 * w, 10 * w, w, w),
	"q": Rect2(0 * w, 11 * w, w, w),
	"r": Rect2(1 * w, 11 * w, w, w),
	"s": Rect2(2 * w, 11 * w, w, w),
	"t": Rect2(3 * w, 11 * w, w, w),
	"u": Rect2(4 * w, 11 * w, w, w),
	"v": Rect2(5 * w, 11 * w, w, w),
	"w": Rect2(6 * w, 11 * w, w, w),
	"x": Rect2(7 * w, 11 * w, w, w),
	"y": Rect2(0 * w, 12 * w, w, w),
	"z": Rect2(1 * w, 12 * w, w, w),
}
